// Actividades de entrenamiento por nivel
export const TRAINING_ACTIVITIES = {
    INICIAL: {
        1: {
            activity: 'CARDIO: Caminata intensa',
            warmup: 'na',
            exercise: 12,
            details: {
                type: 'CARDIO',
                duration: 12,
                exercises: ['Caminata intensa - 12 min']
            }
        },
        2: {
            activity: 'CARDIO: Activación Lateral + DR',
            warmup: 'na',
            exercise: 12,
            details: {
                type: 'CARDIO',
                duration: 12,
                restBetweenSets: '30 a 60 segs',
                exercises: [
                    'Activación Lateral: 6 min',
                    'DR (Directa/Reversa): 6 min'
                ]
            }
        },
        3: {
            activity: 'FLEXIBILIDAD',
            warmup: 3,
            exercise: 12,
            details: {
                type: 'FLEXIBILIDAD',
                duration: 12,
                warmup: 'Precalentamiento: 3 min',
                restBetweenSets: '30 a 60 segs',
                exercises: [
                    'Aplausos del Colibrí: 2 sets - 30 reps c/set',
                    'Vórtice pendular: 1 set - 30 reps',
                    'Toque cruzado: 2 sets - 30 reps c/set',
                    'Sembrando movimiento: 1 set - 30 reps',
                    'Incentivo a la Flexibilidad: 5 min'
                ]
            }
        },
        4: {
            activity: 'FUERZA',
            warmup: 3,
            exercise: 12,
            details: {
                type: 'FUERZA',
                duration: 12,
                warmup: 'Precalentamiento: 3 min',
                restBetweenSets: '30 a 60 segs',
                exercises: [
                    'Flexión Vertical: 2 sets - 30 reps c/set',
                    'Abandonar la silla: 1 set - 30 reps',
                    'Activador Zen: 1 set - 30 reps',
                    'Puente de Glúteos: 2 sets - 30 reps c/set',
                    'Abdominal Supino: 2 sets - 4 reps c/set',
                    'Reductor Cintura: 2 sets - 20 reps c/ pierna c/set'
                ]
            }
        },
        5: {
            activity: 'CARDIO: Activación Lateral + Escaleras',
            warmup: 'na',
            exercise: 12,
            details: {
                type: 'CARDIO',
                duration: 12,
                restBetweenSets: '30 a 60 segs',
                exercises: [
                    'Activación Lateral: 6 min',
                    'S/B Escaleras o Step: 6 min'
                ]
            }
        },
        6: {
            activity: 'CARDIO: Caminata intensa',
            warmup: 'na',
            exercise: 12,
            details: {
                type: 'CARDIO',
                duration: 12,
                exercises: ['Caminata intensa - 12 min']
            }
        },
        7: {
            activity: 'LIBRE',
            warmup: 'na',
            exercise: 'na',
            details: {
                type: 'LIBRE',
                duration: 'na',
                exercises: ['Día libre - Descanso activo']
            }
        },
        8: { activity: 'Caminata intensa', warmup: 'na', exercise: 13 },
        9: { activity: 'AFm2', warmup: 2, exercise: 13 },
        10: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 13 },
        11: { activity: 'AFm2', warmup: 2, exercise: 13 },
        12: { activity: 'Caminata intensa', warmup: 'na', exercise: 13 },
        13: { activity: 'AFm2', warmup: 2, exercise: 13 },
        14: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        15: { activity: 'Caminata intensa', warmup: 'na', exercise: 14 },
        16: { activity: 'AFm2', warmup: 2, exercise: 14 },
        17: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 14 },
        18: { activity: 'AFm2', warmup: 2, exercise: 14 },
        19: { activity: 'Caminata intensa', warmup: 'na', exercise: 14 },
        20: { activity: 'AFm2', warmup: 2, exercise: 14 },
        21: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        22: { activity: 'Caminata intensa', warmup: 'na', exercise: 15 },
        23: { activity: 'AFm2', warmup: 2, exercise: 15 },
        24: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 15 },
        25: { activity: 'AFm2', warmup: 2, exercise: 15 },
        26: { activity: 'Caminata intensa', warmup: 'na', exercise: 15 },
        27: { activity: 'AFm2', warmup: 2, exercise: 15 },
        28: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        29: { activity: 'Caminata intensa', warmup: 'na', exercise: 16 },
        30: { activity: 'AFm2', warmup: 2, exercise: 16 },
        31: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 16 },
        32: { activity: 'AFm2', warmup: 2, exercise: 16 },
        33: { activity: 'Caminata intensa', warmup: 'na', exercise: 16 },
        34: { activity: 'AFm2', warmup: 2, exercise: 16 },
        35: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        36: { activity: 'Caminata intensa', warmup: 'na', exercise: 17 },
        37: { activity: 'AFm2', warmup: 2, exercise: 17 },
        38: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 17 },
        39: { activity: 'AFm2', warmup: 2, exercise: 17 },
        40: { activity: 'Caminata intensa', warmup: 'na', exercise: 17 },
        41: { activity: 'AFm2', warmup: 2, exercise: 17 },
        42: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        43: { activity: 'Caminata intensa', warmup: 'na', exercise: 18 },
        44: { activity: 'AFm2', warmup: 2, exercise: 18 },
        45: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 18 },
        46: { activity: 'AFm2', warmup: 2, exercise: 18 },
        47: { activity: 'Caminata intensa', warmup: 'na', exercise: 18 },
        48: { activity: 'AFm2', warmup: 2, exercise: 18 },
        49: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        50: { activity: 'Caminata intensa', warmup: 'na', exercise: 20 },
        51: { activity: 'AFm2', warmup: 2, exercise: 20 },
        52: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 20 },
        53: { activity: 'AFm2', warmup: 2, exercise: 20 },
        54: { activity: 'Caminata intensa', warmup: 'na', exercise: 20 },
        55: { activity: 'AFm2', warmup: 2, exercise: 20 },
        56: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        57: { activity: 'Caminata intensa', warmup: 'na', exercise: 22 },
        58: { activity: 'AFm2', warmup: 2, exercise: 22 },
        59: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 22 },
        60: { activity: 'AFm2', warmup: 2, exercise: 22 },
        61: { activity: 'Caminata intensa', warmup: 'na', exercise: 22 },
        62: { activity: 'AFm2', warmup: 2, exercise: 22 },
        63: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        64: { activity: 'Caminata intensa', warmup: 'na', exercise: 24 },
        65: { activity: 'AFm2', warmup: 2, exercise: 24 },
        66: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 24 },
        67: { activity: 'AFm2', warmup: 2, exercise: 24 },
        68: { activity: 'Caminata intensa', warmup: 'na', exercise: 24 },
        69: { activity: 'AFm2', warmup: 2, exercise: 24 },
        70: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        71: { activity: 'Caminata intensa', warmup: 'na', exercise: 26 },
        72: { activity: 'AFm2', warmup: 2, exercise: 26 },
        73: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 26 },
        74: { activity: 'AFm2', warmup: 2, exercise: 26 },
        75: { activity: 'Caminata intensa', warmup: 'na', exercise: 26 },
        76: { activity: 'AFm2', warmup: 2, exercise: 26 },
        77: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        78: { activity: 'Caminata intensa', warmup: 'na', exercise: 28 },
        79: { activity: 'AFm2', warmup: 2, exercise: 28 },
        80: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 28 },
        81: { activity: 'AFm2', warmup: 2, exercise: 28 },
        82: { activity: 'Caminata intensa', warmup: 'na', exercise: 28 },
        83: { activity: 'AFm2', warmup: 2, exercise: 28 },
        84: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        85: { activity: 'Caminata intensa', warmup: 'na', exercise: 30 },
        86: { activity: 'AFm2', warmup: 2, exercise: 30 },
        87: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 30 },
        88: { activity: 'AFm2', warmup: 2, exercise: 30 }
    },
    FUNCIONAL: {
        1: { activity: 'Caminata intensa', warmup: 'na', exercise: 15 },
        2: { activity: 'AFm2', warmup: 2, exercise: 15 },
        3: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 15 },
        4: { activity: 'AFm2', warmup: 2, exercise: 15 },
        5: { activity: 'Caminata intensa', warmup: 'na', exercise: 15 },
        6: { activity: 'AFm2', warmup: 2, exercise: 15 },
        7: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        8: { activity: 'Caminata intensa', warmup: 'na', exercise: 16 },
        9: { activity: 'AFm2', warmup: 2, exercise: 16 },
        10: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 16 },
        11: { activity: 'AFm2', warmup: 2, exercise: 16 },
        12: { activity: 'Caminata intensa', warmup: 'na', exercise: 16 },
        13: { activity: 'AFm2', warmup: 2, exercise: 16 },
        14: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        15: { activity: 'Caminata intensa', warmup: 'na', exercise: 18 },
        16: { activity: 'AFm2', warmup: 2, exercise: 18 },
        17: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 18 },
        18: { activity: 'AFm2', warmup: 2, exercise: 18 },
        19: { activity: 'Caminata intensa', warmup: 'na', exercise: 18 },
        20: { activity: 'AFm2', warmup: 2, exercise: 18 },
        21: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        22: { activity: 'Caminata intensa', warmup: 'na', exercise: 20 },
        23: { activity: 'AFm2', warmup: 2, exercise: 20 },
        24: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 20 },
        25: { activity: 'AFm2', warmup: 2, exercise: 20 },
        26: { activity: 'Caminata intensa', warmup: 'na', exercise: 20 },
        27: { activity: 'AFm2', warmup: 2, exercise: 20 },
        28: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        29: { activity: 'Caminata intensa', warmup: 'na', exercise: 22 },
        30: { activity: 'AFm2', warmup: 2, exercise: 22 },
        31: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 22 },
        32: { activity: 'AFm2', warmup: 2, exercise: 22 },
        33: { activity: 'Caminata intensa', warmup: 'na', exercise: 22 },
        34: { activity: 'AFm2', warmup: 2, exercise: 22 },
        35: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        36: { activity: 'Caminata intensa', warmup: 'na', exercise: 24 },
        37: { activity: 'AFm2', warmup: 2, exercise: 24 },
        38: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 24 },
        39: { activity: 'AFm2', warmup: 2, exercise: 24 },
        40: { activity: 'Caminata intensa', warmup: 'na', exercise: 24 },
        41: { activity: 'AFm2', warmup: 2, exercise: 24 },
        42: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        43: { activity: 'Caminata intensa', warmup: 'na', exercise: 27 },
        44: { activity: 'AFm2', warmup: 2, exercise: 27 },
        45: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 27 },
        46: { activity: 'AFm2', warmup: 2, exercise: 27 },
        47: { activity: 'Caminata intensa', warmup: 'na', exercise: 27 },
        48: { activity: 'AFm2', warmup: 2, exercise: 27 },
        49: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        50: { activity: 'Caminata intensa', warmup: 'na', exercise: 30 },
        51: { activity: 'AFm2', warmup: 2, exercise: 30 },
        52: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 30 },
        53: { activity: 'AFm2', warmup: 2, exercise: 30 },
        54: { activity: 'Caminata intensa', warmup: 'na', exercise: 30 },
        55: { activity: 'AFm2', warmup: 2, exercise: 30 },
        56: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        57: { activity: 'Caminata intensa', warmup: 'na', exercise: 33 },
        58: { activity: 'AFm2', warmup: 2, exercise: 33 },
        59: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 33 },
        60: { activity: 'AFm2', warmup: 2, exercise: 33 },
        61: { activity: 'Caminata intensa', warmup: 'na', exercise: 33 },
        62: { activity: 'AFm2', warmup: 2, exercise: 33 },
        63: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        64: { activity: 'Caminata intensa', warmup: 'na', exercise: 36 },
        65: { activity: 'AFm2', warmup: 2, exercise: 36 },
        66: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 36 },
        67: { activity: 'AFm2', warmup: 2, exercise: 36 },
        68: { activity: 'Caminata intensa', warmup: 'na', exercise: 36 },
        69: { activity: 'AFm2', warmup: 2, exercise: 36 },
        70: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        71: { activity: 'Caminata intensa', warmup: 'na', exercise: 39 },
        72: { activity: 'AFm2', warmup: 2, exercise: 39 },
        73: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 39 },
        74: { activity: 'AFm2', warmup: 2, exercise: 39 },
        75: { activity: 'Caminata intensa', warmup: 'na', exercise: 39 },
        76: { activity: 'AFm2', warmup: 2, exercise: 39 },
        77: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        78: { activity: 'Caminata intensa', warmup: 'na', exercise: 42 },
        79: { activity: 'AFm2', warmup: 2, exercise: 42 },
        80: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 42 },
        81: { activity: 'AFm2', warmup: 2, exercise: 42 },
        82: { activity: 'Caminata intensa', warmup: 'na', exercise: 42 },
        83: { activity: 'AFm2', warmup: 2, exercise: 42 },
        84: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        85: { activity: 'Caminata intensa', warmup: 'na', exercise: 45 },
        86: { activity: 'AFm2', warmup: 2, exercise: 45 },
        87: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 45 },
        88: { activity: 'AFm2', warmup: 2, exercise: 45 }
    },
    IDEAL: {
        1: { activity: 'Caminata intensa', warmup: 'na', exercise: 30 },
        2: { activity: 'AFm2', warmup: 2, exercise: 30 },
        3: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 30 },
        4: { activity: 'AFm2', warmup: 2, exercise: 30 },
        5: { activity: 'Caminata intensa', warmup: 'na', exercise: 30 },
        6: { activity: 'AFm2', warmup: 2, exercise: 30 },
        7: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        8: { activity: 'Caminata intensa', warmup: 'na', exercise: 33 },
        9: { activity: 'AFm2', warmup: 2, exercise: 33 },
        10: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 33 },
        11: { activity: 'AFm2', warmup: 2, exercise: 33 },
        12: { activity: 'Caminata intensa', warmup: 'na', exercise: 33 },
        13: { activity: 'AFm2', warmup: 2, exercise: 33 },
        14: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        15: { activity: 'Caminata intensa', warmup: 'na', exercise: 36 },
        16: { activity: 'AFm2', warmup: 2, exercise: 36 },
        17: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 36 },
        18: { activity: 'AFm2', warmup: 2, exercise: 36 },
        19: { activity: 'Caminata intensa', warmup: 'na', exercise: 36 },
        20: { activity: 'AFm2', warmup: 2, exercise: 36 },
        21: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        22: { activity: 'Caminata intensa', warmup: 'na', exercise: 39 },
        23: { activity: 'AFm2', warmup: 2, exercise: 39 },
        24: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 39 },
        25: { activity: 'AFm2', warmup: 2, exercise: 39 },
        26: { activity: 'Caminata intensa', warmup: 'na', exercise: 39 },
        27: { activity: 'AFm2', warmup: 2, exercise: 39 },
        28: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        29: { activity: 'Caminata intensa', warmup: 'na', exercise: 42 },
        30: { activity: 'AFm2', warmup: 2, exercise: 42 },
        31: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 42 },
        32: { activity: 'AFm2', warmup: 2, exercise: 42 },
        33: { activity: 'Caminata intensa', warmup: 'na', exercise: 42 },
        34: { activity: 'AFm2', warmup: 2, exercise: 42 },
        35: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        36: { activity: 'Caminata intensa', warmup: 'na', exercise: 45 },
        37: { activity: 'AFm2', warmup: 2, exercise: 45 },
        38: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 45 },
        39: { activity: 'AFm2', warmup: 2, exercise: 45 },
        40: { activity: 'Caminata intensa', warmup: 'na', exercise: 45 },
        41: { activity: 'AFm2', warmup: 2, exercise: 45 },
        42: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        43: { activity: 'Caminata intensa', warmup: 'na', exercise: 48 },
        44: { activity: 'AFm2', warmup: 2, exercise: 48 },
        45: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 48 },
        46: { activity: 'AFm2', warmup: 2, exercise: 48 },
        47: { activity: 'Caminata intensa', warmup: 'na', exercise: 48 },
        48: { activity: 'AFm2', warmup: 2, exercise: 48 },
        49: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        50: { activity: 'Caminata intensa', warmup: 'na', exercise: 51 },
        51: { activity: 'AFm2', warmup: 2, exercise: 51 },
        52: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 51 },
        53: { activity: 'AFm2', warmup: 2, exercise: 51 },
        54: { activity: 'Caminata intensa', warmup: 'na', exercise: 51 },
        55: { activity: 'AFm2', warmup: 2, exercise: 51 },
        56: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        57: { activity: 'Caminata intensa', warmup: 'na', exercise: 54 },
        58: { activity: 'AFm2', warmup: 2, exercise: 54 },
        59: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 54 },
        60: { activity: 'AFm2', warmup: 2, exercise: 54 },
        61: { activity: 'Caminata intensa', warmup: 'na', exercise: 54 },
        62: { activity: 'AFm2', warmup: 2, exercise: 54 },
        63: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        64: { activity: 'Caminata intensa', warmup: 'na', exercise: 57 },
        65: { activity: 'AFm2', warmup: 2, exercise: 57 },
        66: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 57 },
        67: { activity: 'AFm2', warmup: 2, exercise: 57 },
        68: { activity: 'Caminata intensa', warmup: 'na', exercise: 57 },
        69: { activity: 'AFm2', warmup: 2, exercise: 57 },
        70: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        71: { activity: 'Caminata intensa', warmup: 'na', exercise: 60 },
        72: { activity: 'AFm2', warmup: 2, exercise: 60 },
        73: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 60 },
        74: { activity: 'AFm2', warmup: 2, exercise: 60 },
        75: { activity: 'Caminata intensa', warmup: 'na', exercise: 60 },
        76: { activity: 'AFm2', warmup: 2, exercise: 60 },
        77: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        78: { activity: 'Caminata intensa', warmup: 'na', exercise: 60 },
        79: { activity: 'AFm2', warmup: 2, exercise: 60 },
        80: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 60 },
        81: { activity: 'AFm2', warmup: 2, exercise: 60 },
        82: { activity: 'Caminata intensa', warmup: 'na', exercise: 60 },
        83: { activity: 'AFm2', warmup: 2, exercise: 60 },
        84: { activity: 'Libre', warmup: 'na', exercise: 'na' },
        85: { activity: 'Caminata intensa', warmup: 'na', exercise: 60 },
        86: { activity: 'AFm2', warmup: 2, exercise: 60 },
        87: { activity: 'Subir/B escaleras', warmup: 'na', exercise: 60 },
        88: { activity: 'AFm2', warmup: 2, exercise: 60 }
    }
};

export const getActivityForDay = (level: string, dayNumber: number) => {
    const levelActivities = TRAINING_ACTIVITIES[level as keyof typeof TRAINING_ACTIVITIES];
    return levelActivities ? levelActivities[dayNumber as keyof typeof levelActivities] : null;
};
